# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: WAL.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class WALEntryOpType(betterproto.Enum):
    BEGIN = 0
    SET = 1
    UNSET = 2
    COMMIT = 3
    ROLLBACK = 4


@dataclass
class WALEntry(betterproto.Message):
    crc32: int = betterproto.int64_field(1)
    timestamp: int = betterproto.int64_field(2)
    op_type: "WALEntryOpType" = betterproto.enum_field(3)
    key: str = betterproto.string_field(4)
    value: str = betterproto.string_field(5)


@dataclass
class WAL(betterproto.Message):
    entries: List["WALEntry"] = betterproto.message_field(1)
